# Generated by Django 4.1.3 on 2024-08-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letseatapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image_url',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/9/91/Tom%27s_Restaurant%2C_Manhattan.jpg', max_length=1000),
            preserve_default=False,
        ),
    ]
