# Generated by Django 4.1.3 on 2024-08-24 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letseatapi', '0002_restaurant_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedrestaurant',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='letseatapi.user'),
            preserve_default=False,
        ),
    ]
