# Generated by Django 4.1.3 on 2024-08-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letseatapi', '0004_alter_restaurant_city_alter_restaurant_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='joined',
            field=models.BooleanField(default=False),
        ),
    ]
