# Generated by Django 4.1.3 on 2024-08-26 23:48

from django.db import migrations, models
import letseatapi.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('letseatapi', '0005_restaurant_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='Piethon789?', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default=letseatapi.models.user.generate_uid, max_length=255),
        ),
    ]
