# Generated by Django 4.1.3 on 2024-09-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letseatapi', '0007_user_bio_user_city_user_profile_picture_user_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
