# Generated by Django 4.1.3 on 2024-09-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letseatapi', '0011_alter_user_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
