# Generated by Django 4.1.3 on 2024-09-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letseatapi', '0012_remove_user_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='user_20240909T205630675527+0000', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
