# Generated by Django 4.1.3 on 2024-09-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letseatapi', '0013_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
